### ISSUE TITLE
(SOLVED) just a stupid questions, sorry

### ISSUE THREAD

**Issue by brian12112** [AlexNe/arduino_lanc_sample#1]
I've problem when compiling the code. Its says "'A2' was not declared in this scope"
Can you please help? Thank you

**Comment by AlexNe** [comment]
'A2' it`s a pin arduino. This code for Arduino IDE only. Arduino IDE must have A2 or you Arduino controller don`t have pin A2

**Comment by brian12112** [comment]
Yes I know, What I mean is no declare for Pin 2 (function statement ) .....
  if(analogRead(A2)==0  ) //This is the error says 'A2' was not declared in this scope
  {
    if(setRec){
      setRec=0;
      sendCMD(typeVTR, B00110011); // start/stop
      //sendCMD(typeVTR, B00111001); // photo
      //sendCMD(typeVTR, B00101011); // photo
    }
  }
  else  setRec=1; 
}
.....
or maybe I still need Libraries? thank you

**Comment by brian12112** [comment]
Yes. sorry, I compile it after Uploading other sketches to my esp, so its wrong selecting board.
I close this (shame) issue

**Comment by brian12112** [comment]
Sorry, Im so stupid! Im compiling it after uload code to my esp, Wrong selecting board.
And sorry for long replied. Its working great, and Im sucessfully adding other commands to control my camera
