### ISSUE TITLE
Extra Component

### ISSUE THREAD

**Issue by wrldtvlr** [AlexNe/arduino_lanc_sample#2]
This is a very old project, but I hope someone is still monitoring it. I wanted to know what component was being shown in the photo that does not appear on the schematic. Just above the transistor, there is a a tall silver can. This isn't the diode or resistors and nothing else is on the schematic.

**Comment by AlexNe** [comment]
2 resistors, zener diode, transistor, tantalum capacitor

**Comment by AlexNe** [comment]
https://github.com/AlexNe/arduino_lanc_sample/blob/master/Screenshot_layout.jpg

**Comment by wrldtvlr** [comment]
Ahh... It was a capacitor. Thank you.
